# Common useless comment
### Useless separator comment to obstaculize
# Common useless comment
### Useless separator comment to obstaculize
@api = jsonplaceholder.typicode.com
@user = twodigitss

# Common useless comment
### Get weather forecast
GET https://{{api}}/todos/1
Content-Type: application/json
Accept: application/json

###Create a post
### Useless separator comment to obstaculize
### Useless separator comment to obstaculize
POST https://{{api}}/posts
# this comment's purpose is to obstaculize the splitter
Content-Type: application/json
Accept: application/json
Token: Bearer jwtstring
# this comment's purpose is to obstaculize the splitter

{
  "title" : "apio test",
  "body" : "sent from apio",
  "userId" : 3
}
