# Common useless comment
### Useless separator comment to obstaculize
# Common useless comment
### Useless separator comment to obstaculize
@api = jsonplaceholder.typicode.com
@user = twodigitss

### Get user
GET https://{{api}}/users/5
Content-Type: application/json
Accept: application/json

###Create a post
### Useless separator comment to obstaculize
### Useless separator comment to obstaculize
POST https://{{api}}/posts
# this comment's purpose is to obstaculize the splitter
Content-Type: application/json
Accept: application/json
Token: Bearer jwtstring
# this comment's purpose is to obstaculize the splitter

{
  "title" : "apio test",
  "body" : "sent from apio",
  "user": "{{user}}",
  "userId" : 3
}

### Get user
DELETE https://{{api}}/users/1
Accept: application/json

### Get user
PATCH https://{{api}}/users/1
Accept: application/json

### Get user
HEAD https://{{api}}/users/1
Accept: application/json

### Get user
OPTIONS https://{{api}}/users/1
Accept: application/json

### Update a post (ponytail: minimum PUT request)
PUT https://{{api}}/posts/1
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "title": "apio test updated",
  "body": "updated from apio",
  "userId": 3
}
